export const PROD_CREATE_PRODUCT = 'PROD_CREATE_PRODUCT';
export const PROD_UPDATE_PRODUCT = 'PROD_UPDATE_PRODUCT';
export const PROD_DELETE_PRODUCT = 'PROD_DELETE_PRODUCT';
export const PROD_SET_ALL_PRODUCTS = 'PROD_SET_ALL_PRODUCTS';

export const PROD_SET_ERROR = 'PROD_SET_ERROR';
export const PROD_SET_LOADING_TRUE = 'PROD_SET_LOADING_TRUE';

export const PROD_SET_CREATE_ACTION = 'PROD_SET_CREATE_ACTION';
export const PROD_SET_UPDATE_ACTION = 'PROD_SET_UPDATE_ACTION';
export const PROD_SET_DELETE_ACTION = 'PROD_SET_DELETE_ACTION';
export const PROD_UNSET_ACTION = 'PROD_UNSET_ACTION';
